# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Mod properties
mod_version=5.16.0

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.11
loader_version=0.17.3
fapi_version=0.141.3+1.21.11

# Dependencies
energy_version=4.2.0
rei_version=21.11.814

pal_version=1.15.0