# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Mod properties
mod_version=5.13.3

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.5
yarn_version=1.21.5+build.1
loader_version=0.16.10
fapi_version=0.119.5+1.21.5

# Dependencies
energy_version=4.2.0
rei_version=19.0.806

pal_version=1.13.0