method=ctm_compact
matchBlocks=techreborn:iridium_reinforced_stone_storage_block techreborn:iridium_reinforced_stone_storage_block_stairs techreborn:iridium_reinforced_stone_storage_block_slab
tiles=techreborn:block/storage/iridium_reinforced_stone_storage_block 1-4