package techreborn.init;

import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fluids.FluidContainerRegistry;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.oredict.OreDictionary;
import techreborn.items.ItemCells;
import techreborn.items.ItemCrushedOre;
import techreborn.items.ItemDustTiny;
import techreborn.items.ItemDusts;
import techreborn.items.ItemDustsSmall;
import techreborn.items.ItemGems;
import techreborn.items.ItemIngots;
import techreborn.items.ItemNuggets;
import techreborn.items.ItemParts;
import techreborn.items.ItemPlates;
import techreborn.items.ItemPurifiedCrushedOre;
import techreborn.items.ItemRods;
import techreborn.items.ItemUUmatter;
import techreborn.items.armor.ItemGravityChest;
import techreborn.items.armor.ItemLapotronPack;
import techreborn.items.armor.ItemLithiumBatpack;
import techreborn.items.tools.ItemAdvancedDrill;
import techreborn.items.tools.ItemFluidbucket;
import techreborn.items.tools.ItemHammer;
import techreborn.items.tools.ItemOmniTool;
import techreborn.items.tools.ItemRockCutter;
import techreborn.items.tools.ItemTechPda;
import techreborn.util.BucketHandler;
import techreborn.util.LogHelper;
import cpw.mods.fml.common.registry.GameRegistry;

public class ModItems {

    public static Item gems;
    public static Item ingots;
    public static Item nuggets;
	public static Item dusts;
	public static Item smallDusts;
    public static Item tinyDusts;
	public static Item parts;
	public static Item cells;
	public static Item rockCutter;
	public static Item lithiumBatpack;
	public static Item lapotronpack;
	public static Item gravityChest;
	public static Item omniTool;
	public static Item advancedDrill;
	public static Item manuel;
	public static Item uuMatter;
	public static Item plate;
	public static Item rods;
	public static Item crushedOre;
	public static Item purifiedCrushedOre;
	
	public static Item bucketBerylium;
	public static Item bucketcalcium;
	public static Item bucketcalciumcarbonate;
	public static Item bucketChlorite;
	public static Item bucketDeuterium;
	public static Item bucketGlyceryl;
	public static Item bucketHelium;
	public static Item bucketHelium3;
	public static Item bucketHeliumplasma;
	public static Item bucketHydrogen;
	public static Item bucketLithium;
	public static Item bucketMercury;
	public static Item bucketMethane;
	public static Item bucketNitrocoalfuel;
	public static Item bucketNitrofuel;
	public static Item bucketNitrogen;
	public static Item bucketNitrogendioxide;
	public static Item bucketPotassium;
	public static Item bucketSilicon;
	public static Item bucketSodium;
	public static Item bucketSodiumpersulfate;
	public static Item bucketTritium;
	public static Item bucketWolframium;
	
	public static Item hammerIron;
	public static Item hammerDiamond;



	public static void init()
	{
        gems = new ItemGems();
        GameRegistry.registerItem(gems, "gem");
        ingots = new ItemIngots();
        GameRegistry.registerItem(ingots, "ingot");
		dusts = new ItemDusts();
		GameRegistry.registerItem(dusts, "dust");
		smallDusts = new ItemDustsSmall();
		GameRegistry.registerItem(smallDusts, "smallDust");
        tinyDusts = new ItemDustTiny();
        GameRegistry.registerItem(tinyDusts, "tinyDust");
        plate = new ItemPlates();
        GameRegistry.registerItem(plate, "plates");
        nuggets = new ItemNuggets();
        GameRegistry.registerItem(nuggets, "nuggets");
        rods = new ItemRods();
        GameRegistry.registerItem(rods, "rods");
        crushedOre = new ItemCrushedOre();
        GameRegistry.registerItem(crushedOre, "crushedore");
        purifiedCrushedOre = new ItemPurifiedCrushedOre();
        GameRegistry.registerItem(purifiedCrushedOre, "purifiedCrushedOre");
		parts = new ItemParts();
		GameRegistry.registerItem(parts, "part");
		cells = new ItemCells();
		GameRegistry.registerItem(cells, "cell");
		rockCutter = new ItemRockCutter(ToolMaterial.EMERALD);
		GameRegistry.registerItem(rockCutter, "rockCutter");
		lithiumBatpack = new ItemLithiumBatpack(ArmorMaterial.DIAMOND, 7, 1);
		GameRegistry.registerItem(lithiumBatpack, "lithiumBatpack");
		lapotronpack = new ItemLapotronPack(ArmorMaterial.DIAMOND, 7, 1);
		GameRegistry.registerItem(lapotronpack, "lapotronPack");
		omniTool = new ItemOmniTool(ToolMaterial.EMERALD);
		GameRegistry.registerItem(omniTool, "omniTool");
		advancedDrill = new ItemAdvancedDrill();
		GameRegistry.registerItem(advancedDrill, "advancedDrill");
		gravityChest = new ItemGravityChest(ArmorMaterial.DIAMOND, 7, 1);
		GameRegistry.registerItem(gravityChest, "gravitychestplate");
		manuel = new ItemTechPda();
		GameRegistry.registerItem(manuel, "techmanuel");
		uuMatter = new ItemUUmatter();
		GameRegistry.registerItem(uuMatter, "uumatter");
		
		hammerIron = new ItemHammer(80);
		hammerIron.setUnlocalizedName("hammerIron").setContainerItem(hammerIron);
		GameRegistry.registerItem(hammerIron, "hammerIron");
		
		hammerDiamond = new ItemHammer(200);
		hammerDiamond.setUnlocalizedName("hammerDiamond").setContainerItem(hammerDiamond);
		GameRegistry.registerItem(hammerDiamond, "hammerDiamond");
		
		// buckets
		bucketBerylium = new ItemFluidbucket(ModFluids.BlockFluidBerylium);
		bucketBerylium.setUnlocalizedName("bucketberylium").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketBerylium, "bucketberylium");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidberylium", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketBerylium), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidBerylium, bucketBerylium);
		
		bucketcalcium = new ItemFluidbucket(ModFluids.BlockFluidCalcium);
		bucketcalcium.setUnlocalizedName("bucketcalcium").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketcalcium, "bucketcalcium");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidcalcium", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketcalcium), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidCalcium, bucketcalcium);
		
		bucketcalciumcarbonate = new ItemFluidbucket(ModFluids.BlockFluidCalciumCarbonate);
		bucketcalciumcarbonate.setUnlocalizedName("bucketcalciumcarbonate").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketcalciumcarbonate, "bucketcalciumcarbonate");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidcalciumcarbonate", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketcalciumcarbonate), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidCalciumCarbonate, bucketcalciumcarbonate);
		
		bucketChlorite = new ItemFluidbucket(ModFluids.BlockFluidChlorite);
		bucketChlorite.setUnlocalizedName("bucketchlorite").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketChlorite, "bucketcalchlorite");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidchlorite", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketcalciumcarbonate), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidChlorite, bucketChlorite);
		
		bucketDeuterium = new ItemFluidbucket(ModFluids.BlockFluidDeuterium);
		bucketDeuterium.setUnlocalizedName("bucketdeuterium").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketDeuterium, "bucketdeuterium");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluiddeuterium", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketDeuterium), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidDeuterium, bucketDeuterium);
		
		bucketGlyceryl = new ItemFluidbucket(ModFluids.BlockFluidGlyceryl);
		bucketGlyceryl.setUnlocalizedName("bucketglyceryl").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketGlyceryl, "bucketglyceryl");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidglyceryl", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketGlyceryl), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidGlyceryl, bucketGlyceryl);
		
		bucketHelium = new ItemFluidbucket(ModFluids.BlockFluidHelium);
		bucketHelium.setUnlocalizedName("buckethelium").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketHelium, "buckethelium");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidhelium", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketHelium), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidHelium, bucketHelium);
		
		bucketHelium3 = new ItemFluidbucket(ModFluids.BlockFluidHelium3);
		bucketHelium3.setUnlocalizedName("buckethelium3").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketHelium3, "buckethelium3");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidhelium3", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketHelium3), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidHelium3, bucketHelium3);
		
		bucketHeliumplasma = new ItemFluidbucket(ModFluids.BlockFluidHeliumplasma);
		bucketHeliumplasma.setUnlocalizedName("bucketheliumplasma").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketHeliumplasma, "bucketheliumplasma");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidheliumplasma", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketHeliumplasma), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidHeliumplasma, bucketHeliumplasma);
		
		bucketHydrogen = new ItemFluidbucket(ModFluids.BlockFluidHydrogen);
		bucketHydrogen.setUnlocalizedName("buckethydrogen").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketHydrogen, "buckethydrogen");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidhydrogen", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketHydrogen), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidHydrogen, bucketHydrogen);
		
		bucketLithium = new ItemFluidbucket(ModFluids.BlockFluidLithium);
		bucketLithium.setUnlocalizedName("bucketlithium").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketLithium, "bucketlithium");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidlithium", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketLithium), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidLithium, bucketLithium);
		
		bucketMercury = new ItemFluidbucket(ModFluids.BlockFluidMercury);
		bucketMercury.setUnlocalizedName("bucketmercury").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketMercury, "bucketmercury");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidmercury", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketMercury), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidMercury, bucketMercury);
		
		bucketMethane = new ItemFluidbucket(ModFluids.BlockFluidMethane);
		bucketMethane.setUnlocalizedName("bucketmethane").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketMethane, "bucketmethane");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidmethane", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketMethane), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidMethane, bucketMethane);
		
		bucketNitrocoalfuel = new ItemFluidbucket(ModFluids.BlockFluidNitrocoalfuel);
		bucketNitrocoalfuel.setUnlocalizedName("bucketnitrocoalfuel").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketNitrocoalfuel, "bucketnitrocoalfuel");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidnitrocoalfuel", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketNitrocoalfuel), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidNitrocoalfuel, bucketNitrocoalfuel);
		
		bucketNitrofuel = new ItemFluidbucket(ModFluids.BlockFluidNitrofuel);
		bucketNitrofuel.setUnlocalizedName("bucketnitrofuel").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketNitrofuel, "bucketnitrofuel");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidnitrofuel", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketNitrofuel), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidNitrofuel, bucketNitrofuel);
		
		bucketNitrogen = new ItemFluidbucket(ModFluids.BlockFluidNitrogen);
		bucketNitrogen.setUnlocalizedName("bucketnitrogen").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketNitrogen, "bucketnitrogen");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidnitrogen", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketNitrogen), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidNitrogen, bucketNitrogen);
		
		bucketNitrogendioxide = new ItemFluidbucket(ModFluids.BlockFluidNitrogendioxide);
		bucketNitrogendioxide.setUnlocalizedName("bucketnitrogendioxide").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketNitrogendioxide, "bucketnitrogendioxide");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidnitrogendioxide", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketNitrogendioxide), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidNitrogendioxide, bucketNitrogendioxide);
		
		bucketPotassium = new ItemFluidbucket(ModFluids.BlockFluidPotassium);
		bucketPotassium.setUnlocalizedName("bucketpotassium").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketPotassium, "bucketpotassium");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidpotassium", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketPotassium), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidPotassium, bucketPotassium);
		
		bucketSilicon = new ItemFluidbucket(ModFluids.BlockFluidSilicon);
		bucketSilicon.setUnlocalizedName("bucketsilicon").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketSilicon, "bucketsilicon");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidsilicon", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketSilicon), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidSilicon, bucketSilicon);
		
		bucketSodium = new ItemFluidbucket(ModFluids.BlockFluidSodium);
		bucketSodium.setUnlocalizedName("bucketsodium").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketSodium, "bucketsodium");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidsodium", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketSodium), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidSodium, bucketSodium);
		
		bucketSodiumpersulfate = new ItemFluidbucket(ModFluids.BlockFluidSodiumpersulfate);
		bucketSodiumpersulfate.setUnlocalizedName("bucketsodiumpersulfate").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketSodiumpersulfate, "bucketsodiumpersulfate");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidsodiumpersulfate", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketSodiumpersulfate), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidSodiumpersulfate, bucketSodiumpersulfate);
		
		bucketTritium = new ItemFluidbucket(ModFluids.BlockFluidTritium);
		bucketTritium.setUnlocalizedName("buckettritium").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketTritium, "buckettritium");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidtritium", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketTritium), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidTritium, bucketTritium);
		
		bucketWolframium = new ItemFluidbucket(ModFluids.BlockFluidWolframium);
		bucketWolframium.setUnlocalizedName("bucketwolframium").setContainerItem(Items.bucket);
		GameRegistry.registerItem(bucketWolframium, "bucketwolframium");
		FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("fluidwolframium", FluidContainerRegistry.BUCKET_VOLUME), new ItemStack(bucketWolframium), new ItemStack(Items.bucket));
		BucketHandler.INSTANCE.buckets.put(ModFluids.BlockFluidWolframium, bucketWolframium);
			
		MinecraftForge.EVENT_BUS.register(BucketHandler.INSTANCE);


		LogHelper.info("TechReborns Items Loaded");

		registerOreDict();
	}

	public static void registerOreDict()
	{

        // Gems
        OreDictionary.registerOre("gemRuby", new ItemStack(gems, 1, 0));
        OreDictionary.registerOre("gemSapphire", new ItemStack(gems, 1, 1));
        OreDictionary.registerOre("gemPeridot", new ItemStack(gems, 1, 2));
        OreDictionary.registerOre("gemRedGarnet", new ItemStack(gems, 1, 3));
        OreDictionary.registerOre("gemYellowGarnet", new ItemStack(gems, 1, 4));

		// Dusts
		OreDictionary.registerOre("dustAlmandine", new ItemStack(dusts, 1, 0));
		OreDictionary.registerOre("dustAluminumBrass", new ItemStack(dusts, 1, 1));
		OreDictionary.registerOre("dustAluminum", new ItemStack(dusts, 1, 2));
		OreDictionary.registerOre("dustAluminium", new ItemStack(dusts, 1, 2));
		OreDictionary.registerOre("dustAlumite", new ItemStack(dusts, 1, 3));
		OreDictionary.registerOre("dustAndradite", new ItemStack(dusts, 1, 4));
		OreDictionary.registerOre("dustAntimony", new ItemStack(dusts, 1, 5));
		OreDictionary.registerOre("dustArdite", new ItemStack(dusts, 1, 6));
		OreDictionary.registerOre("dustAsh", new ItemStack(dusts, 1, 7));
		OreDictionary.registerOre("dustBasalt", new ItemStack(dusts, 1, 8));
		OreDictionary.registerOre("dustBauxite", new ItemStack(dusts, 1, 9));
		OreDictionary.registerOre("dustBiotite", new ItemStack(dusts, 1, 10));
		OreDictionary.registerOre("dustBrass", new ItemStack(dusts, 1, 11));
		OreDictionary.registerOre("dustBronze", new ItemStack(dusts, 1, 12));
		OreDictionary.registerOre("dustCadmium", new ItemStack(dusts, 1, 13));
		OreDictionary.registerOre("dustCalcite", new ItemStack(dusts, 1, 14));
		OreDictionary.registerOre("dustCharcoal", new ItemStack(dusts, 1, 15));
		OreDictionary.registerOre("dustChrome", new ItemStack(dusts, 1, 16));
		OreDictionary.registerOre("dustCinnabar", new ItemStack(dusts, 1, 17));
		OreDictionary.registerOre("dustClay", new ItemStack(dusts, 1, 18));
		OreDictionary.registerOre("dustCoal", new ItemStack(dusts, 1, 19));
		OreDictionary.registerOre("dustCobalt", new ItemStack(dusts, 1, 20));
		OreDictionary.registerOre("dustCopper", new ItemStack(dusts, 1, 21));
		OreDictionary.registerOre("dustCupronickel", new ItemStack(dusts, 1, 22));
		OreDictionary.registerOre("dustDarkAsh", new ItemStack(dusts, 1, 23));
		OreDictionary.registerOre("dustDarkIron", new ItemStack(dusts, 1, 24));
		OreDictionary.registerOre("dustDiamond", new ItemStack(dusts, 1, 25));
		OreDictionary.registerOre("dustElectrum", new ItemStack(dusts, 1, 26));
		OreDictionary.registerOre("dustEmerald", new ItemStack(dusts, 1, 27));
		OreDictionary.registerOre("dustEnderEye", new ItemStack(dusts, 1, 28));
		OreDictionary.registerOre("dustEnderPearl", new ItemStack(dusts, 1, 29));
		OreDictionary.registerOre("dustEndstone", new ItemStack(dusts, 1, 30));
		OreDictionary.registerOre("dustFlint", new ItemStack(dusts, 1, 31));
		OreDictionary.registerOre("dustGold", new ItemStack(dusts, 1, 32));
		OreDictionary.registerOre("dustGraphite", new ItemStack(dusts, 1, 33));
		OreDictionary.registerOre("dustGrossular", new ItemStack(dusts, 1, 34));
		OreDictionary.registerOre("dustIndium", new ItemStack(dusts, 1, 35));
		OreDictionary.registerOre("dustInvar", new ItemStack(dusts, 1, 36));
		OreDictionary.registerOre("dustIridium", new ItemStack(dusts, 1, 37));
		OreDictionary.registerOre("dustIron", new ItemStack(dusts, 1, 38));
		OreDictionary.registerOre("dustKanthal", new ItemStack(dusts, 1, 39));
		OreDictionary.registerOre("dustLapis", new ItemStack(dusts, 1, 40));
		OreDictionary.registerOre("dustLazurite", new ItemStack(dusts, 1, 41));
		OreDictionary.registerOre("dustLead", new ItemStack(dusts, 1, 42));
		OreDictionary.registerOre("dustLimestone", new ItemStack(dusts, 1, 43));
		OreDictionary.registerOre("dustLodestone", new ItemStack(dusts, 1, 44));
		OreDictionary.registerOre("dustMagnesium", new ItemStack(dusts, 1, 45));
		OreDictionary.registerOre("dustMagnetite", new ItemStack(dusts, 1, 46));
		OreDictionary.registerOre("dustManganese", new ItemStack(dusts, 1, 47));
		OreDictionary.registerOre("dustManyullyn", new ItemStack(dusts, 1, 48));
		OreDictionary.registerOre("dustMarble", new ItemStack(dusts, 49));
		OreDictionary.registerOre("dustMithril", new ItemStack(dusts, 1, 50));
		OreDictionary.registerOre("dustNetherrack", new ItemStack(dusts, 51));
		OreDictionary.registerOre("dustNichrome", new ItemStack(dusts, 1, 52));
		OreDictionary.registerOre("dustNickel", new ItemStack(dusts, 1, 53));
		OreDictionary.registerOre("dustObsidian", new ItemStack(dusts, 1, 54));
		OreDictionary.registerOre("dustOsmium", new ItemStack(dusts, 1, 55));
		OreDictionary.registerOre("dustPeridot", new ItemStack(dusts, 1, 56));
		OreDictionary.registerOre("dustPhosphorous", new ItemStack(dusts, 1, 57));
		OreDictionary.registerOre("dustPlatinum", new ItemStack(dusts, 1, 58));
		OreDictionary.registerOre("dustPotassiumFeldspar", new ItemStack(dusts, 1, 59));
		OreDictionary.registerOre("dustPyrite", new ItemStack(dusts, 1, 60));
		OreDictionary.registerOre("dustPyrope", new ItemStack(dusts, 1, 61));
		OreDictionary.registerOre("dustRedGarnet", new ItemStack(dusts, 1, 62));
		OreDictionary.registerOre("dustRedrock", new ItemStack(dusts, 1, 63));
		OreDictionary.registerOre("dustRuby", new ItemStack(dusts, 1, 64));
		OreDictionary.registerOre("dustSaltpeter", new ItemStack(dusts, 1, 65));
		OreDictionary.registerOre("dustSapphire", new ItemStack(dusts, 1, 66));
		OreDictionary.registerOre("dustSilver", new ItemStack(dusts, 1, 67));
		OreDictionary.registerOre("dustSilicon", new ItemStack(dusts, 1, 68));
		OreDictionary.registerOre("dustSodalite", new ItemStack(dusts, 1, 69));
		OreDictionary.registerOre("dustSpessartine", new ItemStack(dusts, 1, 70));
		OreDictionary.registerOre("dustSphalerite", new ItemStack(dusts, 1, 71));
		OreDictionary.registerOre("dustSteel", new ItemStack(dusts, 1, 72));
		OreDictionary.registerOre("dustSulfur", new ItemStack(dusts, 1, 73));
		OreDictionary.registerOre("dustTellurium", new ItemStack(dusts, 1, 74));
		OreDictionary.registerOre("dustTeslatite", new ItemStack(dusts, 1, 75));
		OreDictionary.registerOre("dustTetrahedrite", new ItemStack(dusts, 1, 76));
		OreDictionary.registerOre("dustCopper", new ItemStack(dusts, 1, 76));
		OreDictionary.registerOre("dustTin", new ItemStack(dusts, 1, 77));
		OreDictionary.registerOre("dustTitanium", new ItemStack(dusts, 1, 78));
		OreDictionary.registerOre("dustTungsten", new ItemStack(dusts, 1, 79));
		OreDictionary.registerOre("dustUvarovite", new ItemStack(dusts, 1, 80));
		OreDictionary.registerOre("dustVinteum", new ItemStack(dusts, 1, 81));
		OreDictionary.registerOre("dustVoidstone", new ItemStack(dusts, 1, 82));
		OreDictionary.registerOre("dustYellowGarnet", new ItemStack(dusts, 1, 83));
		OreDictionary.registerOre("dustZinc", new ItemStack(dusts, 1, 84));
		OreDictionary.registerOre("dustGalena", new ItemStack(dusts, 1, 85));

		// Small Dusts
		OreDictionary.registerOre("dustSmallAlmandine", new ItemStack(smallDusts, 1, 0));
		OreDictionary.registerOre("dustSmallAluminumBrass", new ItemStack(smallDusts, 1, 1));
		OreDictionary.registerOre("dustSmallAluminum", new ItemStack(smallDusts, 1, 2));
		OreDictionary.registerOre("dustSmallAluminium", new ItemStack(smallDusts, 1, 2));
		OreDictionary.registerOre("dustSmallAlumite", new ItemStack(smallDusts, 1, 3));
		OreDictionary.registerOre("dustSmallAndradite", new ItemStack(smallDusts, 1, 4));
		OreDictionary.registerOre("dustSmallAntimony", new ItemStack(smallDusts, 1, 5));
		OreDictionary.registerOre("dustSmallArdite", new ItemStack(smallDusts, 1, 6));
		OreDictionary.registerOre("dustSmallAsh", new ItemStack(smallDusts, 1, 7));
		OreDictionary.registerOre("dustSmallBasalt", new ItemStack(smallDusts, 1, 8));
		OreDictionary.registerOre("dustSmallBauxite", new ItemStack(smallDusts, 1, 9));
		OreDictionary.registerOre("dustSmallBiotite", new ItemStack(smallDusts, 1, 10));
		OreDictionary.registerOre("dustSmallBrass", new ItemStack(smallDusts, 1, 11));
		OreDictionary.registerOre("dustSmallBronze", new ItemStack(smallDusts, 1, 12));
		OreDictionary.registerOre("dustSmallCadmium", new ItemStack(smallDusts, 1, 13));
		OreDictionary.registerOre("dustSmallCalcite", new ItemStack(smallDusts, 1, 14));
		OreDictionary.registerOre("dustSmallCharcoal", new ItemStack(smallDusts, 1, 15));
		OreDictionary.registerOre("dustSmallChrome", new ItemStack(smallDusts, 1, 16));
		OreDictionary.registerOre("dustSmallCinnabar", new ItemStack(smallDusts, 1, 17));
		OreDictionary.registerOre("dustSmallClay", new ItemStack(smallDusts, 1, 18));
		OreDictionary.registerOre("dustSmallCoal", new ItemStack(smallDusts, 1, 19));
		OreDictionary.registerOre("dustSmallCobalt", new ItemStack(smallDusts, 1, 20));
		OreDictionary.registerOre("dustSmallCopper", new ItemStack(smallDusts, 1, 21));
		OreDictionary.registerOre("dustSmallCupronickel", new ItemStack(smallDusts, 1, 22));
		OreDictionary.registerOre("dustSmallDarkAsh", new ItemStack(smallDusts, 1, 23));
		OreDictionary.registerOre("dustSmallDarkIron", new ItemStack(smallDusts, 1, 24));
		OreDictionary.registerOre("dustSmallDiamond", new ItemStack(smallDusts, 1, 25));
		OreDictionary.registerOre("dustSmallElectrum", new ItemStack(smallDusts, 1, 26));
		OreDictionary.registerOre("dustSmallEmerald", new ItemStack(smallDusts, 1, 27));
		OreDictionary.registerOre("dustSmallEnderEye", new ItemStack(smallDusts, 1, 28));
		OreDictionary.registerOre("dustSmallEnderPearl", new ItemStack(smallDusts, 1, 29));
		OreDictionary.registerOre("dustSmallEndstone", new ItemStack(smallDusts, 1, 30));
		OreDictionary.registerOre("dustSmallFlint", new ItemStack(smallDusts, 1, 31));
        OreDictionary.registerOre("dustSmallGlowstone", new ItemStack(smallDusts, 1, 32));
		OreDictionary.registerOre("dustSmallGold", new ItemStack(smallDusts, 1, 33));
		OreDictionary.registerOre("dustSmallGraphite", new ItemStack(smallDusts, 1, 34));
		OreDictionary.registerOre("dustSmallGrossular", new ItemStack(smallDusts, 1, 35));
        OreDictionary.registerOre("dustSmallGunpowder", new ItemStack(smallDusts, 1, 36));
		OreDictionary.registerOre("dustSmallIndium", new ItemStack(smallDusts, 1, 37));
		OreDictionary.registerOre("dustSmallInvar", new ItemStack(smallDusts, 1, 38));
		OreDictionary.registerOre("dustSmallIridium", new ItemStack(smallDusts, 1, 39));
		OreDictionary.registerOre("dustSmallIron", new ItemStack(smallDusts, 1, 40));
		OreDictionary.registerOre("dustSmallKanthal", new ItemStack(smallDusts, 1, 41));
		OreDictionary.registerOre("dustSmallLapis", new ItemStack(smallDusts, 1, 42));
		OreDictionary.registerOre("dustSmallLazurite", new ItemStack(smallDusts, 1, 43));
		OreDictionary.registerOre("dustSmallLead", new ItemStack(smallDusts, 1, 44));
		OreDictionary.registerOre("dustSmallLimestone", new ItemStack(smallDusts, 1, 45));
		OreDictionary.registerOre("dustSmallLodestone", new ItemStack(smallDusts, 1, 46));
		OreDictionary.registerOre("dustSmallMagnesium", new ItemStack(smallDusts, 1, 47));
		OreDictionary.registerOre("dustSmallMagnetite", new ItemStack(smallDusts, 1, 48));
		OreDictionary.registerOre("dustSmallManganese", new ItemStack(smallDusts, 1, 49));
		OreDictionary.registerOre("dustSmallManyullyn", new ItemStack(smallDusts, 1, 50));
		OreDictionary.registerOre("dustSmallMarble", new ItemStack(smallDusts, 51));
		OreDictionary.registerOre("dustSmallMithril", new ItemStack(smallDusts, 1, 52));
		OreDictionary.registerOre("dustSmallNetherrack", new ItemStack(smallDusts, 53));
		OreDictionary.registerOre("dustSmallNichrome", new ItemStack(smallDusts, 1, 54));
		OreDictionary.registerOre("dustSmallNickel", new ItemStack(smallDusts, 1, 55));
		OreDictionary.registerOre("dustSmallObsidian", new ItemStack(smallDusts, 1, 56));
		OreDictionary.registerOre("dustSmallOsmium", new ItemStack(smallDusts, 1, 57));
		OreDictionary.registerOre("dustSmallPeridot", new ItemStack(smallDusts, 1, 58));
		OreDictionary.registerOre("dustSmallPhosphorous", new ItemStack(smallDusts, 1, 59));
		OreDictionary.registerOre("dustSmallPlatinum", new ItemStack(smallDusts, 1, 60));
		OreDictionary.registerOre("dustSmallPotassiumFeldspar", new ItemStack(smallDusts, 1, 61));
		OreDictionary.registerOre("dustSmallPyrite", new ItemStack(smallDusts, 1, 62));
		OreDictionary.registerOre("dustSmallPyrope", new ItemStack(smallDusts, 1, 63));
		OreDictionary.registerOre("dustSmallRedGarnet", new ItemStack(smallDusts, 1, 64));
		OreDictionary.registerOre("dustSmallRedrock", new ItemStack(smallDusts, 1, 65));
        OreDictionary.registerOre("dustSmallRedstone", new ItemStack(smallDusts, 1, 66));
		OreDictionary.registerOre("dustSmallRuby", new ItemStack(smallDusts, 1, 67));
		OreDictionary.registerOre("dustSmallSaltpeter", new ItemStack(smallDusts, 1, 68));
		OreDictionary.registerOre("dustSmallSapphire", new ItemStack(smallDusts, 1, 69));
		OreDictionary.registerOre("dustSmallSilver", new ItemStack(smallDusts, 1, 70));
		OreDictionary.registerOre("dustSmallSilicon", new ItemStack(smallDusts, 1, 71));
		OreDictionary.registerOre("dustSmallSodalite", new ItemStack(smallDusts, 1, 72));
		OreDictionary.registerOre("dustSmallSpessartine", new ItemStack(smallDusts, 1, 73));
		OreDictionary.registerOre("dustSmallSphalerite", new ItemStack(smallDusts, 1, 74));
		OreDictionary.registerOre("dustSmallSteel", new ItemStack(smallDusts, 1, 75));
		OreDictionary.registerOre("dustSmallSulfur", new ItemStack(smallDusts, 1, 76));
		OreDictionary.registerOre("dustSmallTellurium", new ItemStack(smallDusts, 1, 77));
		OreDictionary.registerOre("dustSmallTeslatite", new ItemStack(smallDusts, 1, 78));
		OreDictionary.registerOre("dustSmallTetrahedrite", new ItemStack(smallDusts, 1, 79));
		OreDictionary.registerOre("dustSmallCopper", new ItemStack(smallDusts, 1, 79));
		OreDictionary.registerOre("dustSmallTin", new ItemStack(smallDusts, 1, 80));
		OreDictionary.registerOre("dustSmallTitanium", new ItemStack(smallDusts, 1, 81));
		OreDictionary.registerOre("dustSmallTungsten", new ItemStack(smallDusts, 1, 82));
		OreDictionary.registerOre("dustSmallUvarovite", new ItemStack(smallDusts, 1, 83));
		OreDictionary.registerOre("dustSmallVinteum", new ItemStack(smallDusts, 1, 84));
		OreDictionary.registerOre("dustSmallVoidstone", new ItemStack(smallDusts, 1, 85));
		OreDictionary.registerOre("dustSmallYellowGarnet", new ItemStack(smallDusts, 1, 86));
		OreDictionary.registerOre("dustSmallZinc", new ItemStack(smallDusts, 1, 87));
		OreDictionary.registerOre("dustSmallGalena", new ItemStack(smallDusts, 1, 88));

        // Tiny Dusts
        OreDictionary.registerOre("dustTinyAlmandine", new ItemStack(tinyDusts, 1, 0));
        OreDictionary.registerOre("dustTinyAluminumBrass", new ItemStack(tinyDusts, 1, 1));
        OreDictionary.registerOre("dustTinyAluminum", new ItemStack(tinyDusts, 1, 2));
        OreDictionary.registerOre("dustTinyAluminium", new ItemStack(tinyDusts, 1, 2));
        OreDictionary.registerOre("dustTinyAlumite", new ItemStack(tinyDusts, 1, 3));
        OreDictionary.registerOre("dustTinyAndradite", new ItemStack(tinyDusts, 1, 4));
        OreDictionary.registerOre("dustTinyAntimony", new ItemStack(tinyDusts, 1, 5));
        OreDictionary.registerOre("dustTinyArdite", new ItemStack(tinyDusts, 1, 6));
        OreDictionary.registerOre("dustTinyAsh", new ItemStack(tinyDusts, 1, 7));
        OreDictionary.registerOre("dustTinyBasalt", new ItemStack(tinyDusts, 1, 8));
        OreDictionary.registerOre("dustTinyBauxite", new ItemStack(tinyDusts, 1, 9));
        OreDictionary.registerOre("dustTinyBiotite", new ItemStack(tinyDusts, 1, 10));
        OreDictionary.registerOre("dustTinyBrass", new ItemStack(tinyDusts, 1, 11));
        OreDictionary.registerOre("dustTinyBronze", new ItemStack(tinyDusts, 1, 12));
        OreDictionary.registerOre("dustTinyCadmium", new ItemStack(tinyDusts, 1, 13));
        OreDictionary.registerOre("dustTinyCalcite", new ItemStack(tinyDusts, 1, 14));
        OreDictionary.registerOre("dustTinyCharcoal", new ItemStack(tinyDusts, 1, 15));
        OreDictionary.registerOre("dustTinyChrome", new ItemStack(tinyDusts, 1, 16));
        OreDictionary.registerOre("dustTinyCinnabar", new ItemStack(tinyDusts, 1, 17));
        OreDictionary.registerOre("dustTinyClay", new ItemStack(tinyDusts, 1, 18));
        OreDictionary.registerOre("dustTinyCoal", new ItemStack(tinyDusts, 1, 19));
        OreDictionary.registerOre("dustTinyCobalt", new ItemStack(tinyDusts, 1, 20));
        OreDictionary.registerOre("dustTinyCopper", new ItemStack(tinyDusts, 1, 21));
        OreDictionary.registerOre("dustTinyCupronickel", new ItemStack(tinyDusts, 1, 22));
        OreDictionary.registerOre("dustTinyDarkAsh", new ItemStack(tinyDusts, 1, 23));
        OreDictionary.registerOre("dustTinyDarkIron", new ItemStack(tinyDusts, 1, 24));
        OreDictionary.registerOre("dustTinyDiamond", new ItemStack(tinyDusts, 1, 25));
        OreDictionary.registerOre("dustTinyElectrum", new ItemStack(tinyDusts, 1, 26));
        OreDictionary.registerOre("dustTinyEmerald", new ItemStack(tinyDusts, 1, 27));
        OreDictionary.registerOre("dustTinyEnderEye", new ItemStack(tinyDusts, 1, 28));
        OreDictionary.registerOre("dustTinyEnderPearl", new ItemStack(tinyDusts, 1, 29));
        OreDictionary.registerOre("dustTinyEndstone", new ItemStack(tinyDusts, 1, 30));
        OreDictionary.registerOre("dustTinyFlint", new ItemStack(tinyDusts, 1, 31));
        OreDictionary.registerOre("dustTinyGlowstone", new ItemStack(tinyDusts, 1, 32));
        OreDictionary.registerOre("dustTinyGold", new ItemStack(tinyDusts, 1, 33));
        OreDictionary.registerOre("dustTinyGraphite", new ItemStack(tinyDusts, 1, 34));
        OreDictionary.registerOre("dustTinyGrossular", new ItemStack(tinyDusts, 1, 35));
        OreDictionary.registerOre("dustTinyGunpowder", new ItemStack(tinyDusts, 1, 36));
        OreDictionary.registerOre("dustTinyIndium", new ItemStack(tinyDusts, 1, 37));
        OreDictionary.registerOre("dustTinyInvar", new ItemStack(tinyDusts, 1, 38));
        OreDictionary.registerOre("dustTinyIridium", new ItemStack(tinyDusts, 1, 39));
        OreDictionary.registerOre("dustTinyIron", new ItemStack(tinyDusts, 1, 40));
        OreDictionary.registerOre("dustTinyKanthal", new ItemStack(tinyDusts, 1, 41));
        OreDictionary.registerOre("dustTinyLapis", new ItemStack(tinyDusts, 1, 42));
        OreDictionary.registerOre("dustTinyLazurite", new ItemStack(tinyDusts, 1, 43));
        OreDictionary.registerOre("dustTinyLead", new ItemStack(tinyDusts, 1, 44));
        OreDictionary.registerOre("dustTinyLimestone", new ItemStack(tinyDusts, 1, 45));
        OreDictionary.registerOre("dustTinyLodestone", new ItemStack(tinyDusts, 1, 46));
        OreDictionary.registerOre("dustTinyMagnesium", new ItemStack(tinyDusts, 1, 47));
        OreDictionary.registerOre("dustTinyMagnetite", new ItemStack(tinyDusts, 1, 48));
        OreDictionary.registerOre("dustTinyManganese", new ItemStack(tinyDusts, 1, 49));
        OreDictionary.registerOre("dustTinyManyullyn", new ItemStack(tinyDusts, 1, 50));
        OreDictionary.registerOre("dustTinyMarble", new ItemStack(tinyDusts, 51));
        OreDictionary.registerOre("dustTinyMithril", new ItemStack(tinyDusts, 1, 52));
        OreDictionary.registerOre("dustTinyNetherrack", new ItemStack(tinyDusts, 53));
        OreDictionary.registerOre("dustTinyNichrome", new ItemStack(tinyDusts, 1, 54));
        OreDictionary.registerOre("dustTinyNickel", new ItemStack(tinyDusts, 1, 55));
        OreDictionary.registerOre("dustTinyObsidian", new ItemStack(tinyDusts, 1, 56));
        OreDictionary.registerOre("dustTinyOsmium", new ItemStack(tinyDusts, 1, 57));
        OreDictionary.registerOre("dustTinyPeridot", new ItemStack(tinyDusts, 1, 58));
        OreDictionary.registerOre("dustTinyPhosphorous", new ItemStack(tinyDusts, 1, 59));
        OreDictionary.registerOre("dustTinyPlatinum", new ItemStack(tinyDusts, 1, 60));
        OreDictionary.registerOre("dustTinyPotassiumFeldspar", new ItemStack(tinyDusts, 1, 61));
        OreDictionary.registerOre("dustTinyPyrite", new ItemStack(tinyDusts, 1, 62));
        OreDictionary.registerOre("dustTinyPyrope", new ItemStack(tinyDusts, 1, 63));
        OreDictionary.registerOre("dustTinyRedGarnet", new ItemStack(tinyDusts, 1, 64));
        OreDictionary.registerOre("dustTinyRedrock", new ItemStack(tinyDusts, 1, 65));
        OreDictionary.registerOre("dustTinyRedstone", new ItemStack(tinyDusts, 1, 66));
        OreDictionary.registerOre("dustTinyRuby", new ItemStack(tinyDusts, 1, 67));
        OreDictionary.registerOre("dustTinySaltpeter", new ItemStack(tinyDusts, 1, 68));
        OreDictionary.registerOre("dustTinySapphire", new ItemStack(tinyDusts, 1, 69));
        OreDictionary.registerOre("dustTinySilver", new ItemStack(tinyDusts, 1, 70));
        OreDictionary.registerOre("dustTinySilicon", new ItemStack(tinyDusts, 1, 71));
        OreDictionary.registerOre("dustTinySodalite", new ItemStack(tinyDusts, 1, 72));
        OreDictionary.registerOre("dustTinySpessartine", new ItemStack(tinyDusts, 1, 73));
        OreDictionary.registerOre("dustTinySphalerite", new ItemStack(tinyDusts, 1, 74));
        OreDictionary.registerOre("dustTinySteel", new ItemStack(tinyDusts, 1, 75));
        OreDictionary.registerOre("dustTinySulfur", new ItemStack(tinyDusts, 1, 76));
        OreDictionary.registerOre("dustTinyTellurium", new ItemStack(tinyDusts, 1, 77));
        OreDictionary.registerOre("dustTinyTeslatite", new ItemStack(tinyDusts, 1, 78));
        OreDictionary.registerOre("dustTinyTetrahedrite", new ItemStack(tinyDusts, 1, 79));
        OreDictionary.registerOre("dustTinyCopper", new ItemStack(tinyDusts, 1, 79));
        OreDictionary.registerOre("dustTinyTin", new ItemStack(tinyDusts, 1, 80));
        OreDictionary.registerOre("dustTinyTitanium", new ItemStack(tinyDusts, 1, 81));
        OreDictionary.registerOre("dustTinyTungsten", new ItemStack(tinyDusts, 1, 82));
        OreDictionary.registerOre("dustTinyUvarovite", new ItemStack(tinyDusts, 1, 83));
        OreDictionary.registerOre("dustTinyVinteum", new ItemStack(tinyDusts, 1, 84));
        OreDictionary.registerOre("dustTinyVoidstone", new ItemStack(tinyDusts, 1, 85));
        OreDictionary.registerOre("dustTinyYellowGarnet", new ItemStack(tinyDusts, 1, 86));
        OreDictionary.registerOre("dustTinyZinc", new ItemStack(tinyDusts, 1, 87));
		OreDictionary.registerOre("dustTinyGalena", new ItemStack(tinyDusts, 1, 88));

		// Ingots
		OreDictionary.registerOre("ingotAluminum", new ItemStack(ingots, 1, 0));
		OreDictionary.registerOre("ingotAluminium", new ItemStack(ingots, 1, 0));
		OreDictionary.registerOre("ingotAntimony", new ItemStack(ingots, 1, 1));
		OreDictionary.registerOre("ingotBatteryAlloy", new ItemStack(ingots, 1, 2));
		OreDictionary.registerOre("ingotBlueAlloy", new ItemStack(ingots, 1, 4));
		OreDictionary.registerOre("ingotBrass", new ItemStack(ingots, 1, 5));
		OreDictionary.registerOre("ingotBronze", new ItemStack(ingots, 1, 6));
		OreDictionary.registerOre("ingotCadmium", new ItemStack(ingots, 1, 7));
		OreDictionary.registerOre("ingotChrome", new ItemStack(ingots, 1, 8));
		OreDictionary.registerOre("ingotCopper", new ItemStack(ingots, 1, 9));
		OreDictionary.registerOre("ingotCupronickel", new ItemStack(ingots, 1, 10));
		OreDictionary.registerOre("ingotElectrum", new ItemStack(ingots, 1, 11));
		OreDictionary.registerOre("ingotIndium", new ItemStack(ingots, 1, 12));
		OreDictionary.registerOre("ingotInvar", new ItemStack(ingots, 1, 13));
		OreDictionary.registerOre("ingotIridium", new ItemStack(ingots, 1, 14));
		OreDictionary.registerOre("ingotKanthal", new ItemStack(ingots, 1, 15));
		OreDictionary.registerOre("ingotLead", new ItemStack(ingots, 1, 16));
		OreDictionary.registerOre("ingotLodestone", new ItemStack(ingots, 1, 17));
		OreDictionary.registerOre("ingotMagnalium", new ItemStack(ingots, 1, 18));
		OreDictionary.registerOre("ingotNichrome", new ItemStack(ingots, 1, 19));
		OreDictionary.registerOre("ingotNickel", new ItemStack(ingots, 1, 20));
		OreDictionary.registerOre("ingotOsmium", new ItemStack(ingots, 1, 21));
		OreDictionary.registerOre("ingotPlatinum", new ItemStack(ingots, 1, 22));
		OreDictionary.registerOre("ingotRedAlloy", new ItemStack(ingots, 1, 3));
		OreDictionary.registerOre("ingotSilver", new ItemStack(ingots, 1, 23));
		OreDictionary.registerOre("ingotSteel", new ItemStack(ingots, 1, 24));
		OreDictionary.registerOre("ingotTellurium", new ItemStack(ingots, 1, 25));
		OreDictionary.registerOre("ingotTin", new ItemStack(ingots, 1, 26));
		OreDictionary.registerOre("ingotTitanium", new ItemStack(ingots, 1, 27));
		OreDictionary.registerOre("ingotTungsten", new ItemStack(ingots, 1, 28));
		OreDictionary.registerOre("ingotTungstensteel", new ItemStack(ingots, 1, 30));
		OreDictionary.registerOre("ingotHotTungstenSteel", new ItemStack(ingots, 1, 29));
		OreDictionary.registerOre("ingotZinc", new ItemStack(ingots, 1, 31));

        // Nuggets
        OreDictionary.registerOre("nuggetAluminum", new ItemStack(nuggets, 1, 0));
        OreDictionary.registerOre("nuggetAluminium", new ItemStack(nuggets, 1, 0));
        OreDictionary.registerOre("nuggetAntimony", new ItemStack(nuggets, 1, 1));
        OreDictionary.registerOre("nuggetBrass", new ItemStack(nuggets, 1, 2));
        OreDictionary.registerOre("nuggetBronze", new ItemStack(nuggets, 1, 3));
        OreDictionary.registerOre("nuggetChrome", new ItemStack(nuggets, 1, 4));
        OreDictionary.registerOre("nuggetCopper", new ItemStack(nuggets, 1, 5));
        OreDictionary.registerOre("nuggetElectrum", new ItemStack(nuggets, 1, 6));
        OreDictionary.registerOre("nuggetInvar", new ItemStack(nuggets, 1, 7));
        OreDictionary.registerOre("nuggetIridium", new ItemStack(nuggets, 1, 8));
        OreDictionary.registerOre("nuggetIron", new ItemStack(nuggets, 1, 9));
        OreDictionary.registerOre("nuggetLead", new ItemStack(nuggets, 1, 10));
        OreDictionary.registerOre("nuggetNickel", new ItemStack(nuggets, 1, 11));
        OreDictionary.registerOre("nuggetOsmium", new ItemStack(nuggets, 1, 12));
        OreDictionary.registerOre("nuggetPlatinum", new ItemStack(nuggets, 1, 13));
        OreDictionary.registerOre("nuggetSilver", new ItemStack(nuggets, 1, 14));
        OreDictionary.registerOre("nuggetSteel", new ItemStack(nuggets, 1, 15));
        OreDictionary.registerOre("nuggetTin", new ItemStack(nuggets, 1, 16));
        OreDictionary.registerOre("nuggetTitanium", new ItemStack(nuggets, 1, 17));
        OreDictionary.registerOre("nuggetTungsten", new ItemStack(nuggets, 1, 18));
        OreDictionary.registerOre("nuggetZinc", new ItemStack(nuggets, 1, 19));

        // Plates
        OreDictionary.registerOre("plateAluminum", new ItemStack(plate, 1, 0));
        OreDictionary.registerOre("plateAluminium", new ItemStack(plate, 1, 0));
        OreDictionary.registerOre("plateBatteryAlloy", new ItemStack(plate, 1, 1));
        OreDictionary.registerOre("plateBrass", new ItemStack(plate, 1, 2));
        OreDictionary.registerOre("plateBronze", new ItemStack(plate, 1, 3));
        OreDictionary.registerOre("plateCoal", new ItemStack(plate, 1, 4));
        OreDictionary.registerOre("plateChrome", new ItemStack(plate, 1, 5));
        OreDictionary.registerOre("plateCopper", new ItemStack(plate, 1, 6));
        OreDictionary.registerOre("plateDiamond", new ItemStack(plate, 1, 7));
        OreDictionary.registerOre("plateElectrum", new ItemStack(plate, 1, 8));
        OreDictionary.registerOre("plateEmerald", new ItemStack(plate, 1, 9));
        OreDictionary.registerOre("plateGold", new ItemStack(plate, 1, 10));
        OreDictionary.registerOre("plateInvar", new ItemStack(plate, 1, 11));
        OreDictionary.registerOre("plateIridium", new ItemStack(plate, 1, 12));
        OreDictionary.registerOre("plateIron", new ItemStack(plate, 1, 13));
        OreDictionary.registerOre("plateLapis", new ItemStack(plate, 1, 14));
        OreDictionary.registerOre("plateLead", new ItemStack(plate, 1, 15));
        OreDictionary.registerOre("plateMagnalium", new ItemStack(plate, 1, 16));
        OreDictionary.registerOre("plateNickel", new ItemStack(plate, 1, 17));
        OreDictionary.registerOre("plateObsidian", new ItemStack(plate, 1, 18));
        OreDictionary.registerOre("plateOsmium", new ItemStack(plate, 1, 19));
        OreDictionary.registerOre("platePeridot", new ItemStack(plate, 1, 20));
        OreDictionary.registerOre("platePlatinum", new ItemStack(plate, 1, 21));
        OreDictionary.registerOre("plateRedGarnet", new ItemStack(plate, 1, 22));
        OreDictionary.registerOre("plateRedstone", new ItemStack(plate, 1, 23));
        OreDictionary.registerOre("plateRedstoneAlloy", new ItemStack(plate, 1, 23));
        OreDictionary.registerOre("plateRuby", new ItemStack(plate, 1, 24));
        OreDictionary.registerOre("plateSapphire", new ItemStack(plate, 1, 25));
        OreDictionary.registerOre("plateSilicon", new ItemStack(plate, 1, 26));
        OreDictionary.registerOre("plateSilver", new ItemStack(plate, 1, 27));
        OreDictionary.registerOre("plateSteel", new ItemStack(plate, 1, 28));
        OreDictionary.registerOre("plateTeslatite", new ItemStack(plate, 1, 29));
        OreDictionary.registerOre("plateTin", new ItemStack(plate, 1, 30));
        OreDictionary.registerOre("plateTitanium", new ItemStack(plate, 1, 31));
        OreDictionary.registerOre("plateTungsten", new ItemStack(plate, 1, 32));
        OreDictionary.registerOre("plateTungstensteel", new ItemStack(plate, 1, 33));
        OreDictionary.registerOre("plateYellowGarnet", new ItemStack(plate, 1, 34));
        OreDictionary.registerOre("plateZinc", new ItemStack(plate, 1, 35));

        // Rods
        OreDictionary.registerOre("stickBrass", new ItemStack(rods, 1, 0));
        OreDictionary.registerOre("stickBronze", new ItemStack(rods, 1, 1));
        OreDictionary.registerOre("stickCopper", new ItemStack(rods, 1, 2));
        OreDictionary.registerOre("stickElectrum", new ItemStack(rods, 1, 3));
        OreDictionary.registerOre("stickGold", new ItemStack(rods, 1, 4));
        OreDictionary.registerOre("stickInvar", new ItemStack(rods, 1, 5));
        OreDictionary.registerOre("stickIridium", new ItemStack(rods, 1, 6));
        OreDictionary.registerOre("stickIron", new ItemStack(rods, 1, 7));
        OreDictionary.registerOre("stickLead", new ItemStack(rods, 1, 8));
        OreDictionary.registerOre("stickNickel", new ItemStack(rods, 1, 9));
        OreDictionary.registerOre("stickPlatinum", new ItemStack(rods, 1, 10));
        OreDictionary.registerOre("stickSilver", new ItemStack(rods, 1, 11));
        OreDictionary.registerOre("stickSteel", new ItemStack(rods, 1, 12));
        OreDictionary.registerOre("stickTin", new ItemStack(rods, 1, 13));
        OreDictionary.registerOre("stickTitanium", new ItemStack(rods, 1, 14));
        OreDictionary.registerOre("stickTungstensteel", new ItemStack(rods, 1, 15));

        // Crushed Ore
        OreDictionary.registerOre("crushedAluminum", new ItemStack(crushedOre, 1, 0));
        OreDictionary.registerOre("crushedAluminium", new ItemStack(crushedOre, 1, 0));
        OreDictionary.registerOre("crushedArdite", new ItemStack(crushedOre, 1, 1));
        OreDictionary.registerOre("crushedBauxite", new ItemStack(crushedOre, 1, 2));
        OreDictionary.registerOre("crushedCadmium", new ItemStack(crushedOre, 1, 3));
        OreDictionary.registerOre("crushedCinnabar", new ItemStack(crushedOre, 1, 4));
        OreDictionary.registerOre("crushedCobalt", new ItemStack(crushedOre, 1, 5));
        OreDictionary.registerOre("crushedDarkIron", new ItemStack(crushedOre, 1, 6));
        OreDictionary.registerOre("crushedIndium", new ItemStack(crushedOre, 1, 7));
        OreDictionary.registerOre("crushedIridium", new ItemStack(crushedOre, 1, 8));
        OreDictionary.registerOre("crushedNickel", new ItemStack(crushedOre, 1, 9));
        OreDictionary.registerOre("crushedOsmium", new ItemStack(crushedOre, 1, 10));
        OreDictionary.registerOre("crushedPlatinum", new ItemStack(crushedOre, 1, 11));
        OreDictionary.registerOre("crushedPyrite", new ItemStack(crushedOre, 1, 12));
        OreDictionary.registerOre("crushedSphalerite", new ItemStack(crushedOre, 1, 13));
        OreDictionary.registerOre("crushedTetrahedrite", new ItemStack(crushedOre, 1, 14));
        OreDictionary.registerOre("crushedTungsten", new ItemStack(crushedOre, 1, 15));
		OreDictionary.registerOre("crushedGalena", new ItemStack(crushedOre, 1, 16));

        // Purified Crushed Ore
        OreDictionary.registerOre("crushedPurifiedAluminum", new ItemStack(purifiedCrushedOre, 1, 0));
        OreDictionary.registerOre("crushedPurifiedAluminium", new ItemStack(purifiedCrushedOre, 1, 0));
        OreDictionary.registerOre("crushedPurifiedArdite", new ItemStack(purifiedCrushedOre, 1, 1));
        OreDictionary.registerOre("crushedPurifiedBauxite", new ItemStack(purifiedCrushedOre, 1, 2));
        OreDictionary.registerOre("crushedPurifiedCadmium", new ItemStack(purifiedCrushedOre, 1, 3));
        OreDictionary.registerOre("crushedPurifiedCinnabar", new ItemStack(purifiedCrushedOre, 1, 4));
        OreDictionary.registerOre("crushedPurifiedCobalt", new ItemStack(purifiedCrushedOre, 1, 5));
        OreDictionary.registerOre("crushedPurifiedDarkIron", new ItemStack(purifiedCrushedOre, 1, 6));
        OreDictionary.registerOre("crushedPurifiedIndium", new ItemStack(purifiedCrushedOre, 1, 7));
        OreDictionary.registerOre("crushedPurifiedIridium", new ItemStack(purifiedCrushedOre, 1, 8));
        OreDictionary.registerOre("crushedPurifiedNickel", new ItemStack(purifiedCrushedOre, 1, 9));
        OreDictionary.registerOre("crushedPurifiedOsmium", new ItemStack(purifiedCrushedOre, 1, 10));
        OreDictionary.registerOre("crushedPurifiedPlatinum", new ItemStack(purifiedCrushedOre, 1, 11));
        OreDictionary.registerOre("crushedPurifiedPyrite", new ItemStack(purifiedCrushedOre, 1, 12));
        OreDictionary.registerOre("crushedPurifiedSphalerite", new ItemStack(purifiedCrushedOre, 1, 13));
        OreDictionary.registerOre("crushedPurifiedTetrahedrite", new ItemStack(purifiedCrushedOre, 1, 14));
        OreDictionary.registerOre("crushedPurifiedTungsten", new ItemStack(purifiedCrushedOre, 1, 15));
		OreDictionary.registerOre("crushedPurifiedGalena", new ItemStack(purifiedCrushedOre, 1, 16));

		// Purified Crushed Ore
		OreDictionary.registerOre("craftingGrinder", new ItemStack(parts, 1, 8));
		OreDictionary.registerOre("craftingGrinder", new ItemStack(parts, 1, 10));
        OreDictionary.registerOre("circuitMaster", new ItemStack(parts, 1, 4));
        OreDictionary.registerOre("circuitElite", new ItemStack(parts, 1, 5));
		OreDictionary.registerOre("craftingSuperconductor", new ItemStack(parts, 1, 30));
		OreDictionary.registerOre("batteryUltimate", new ItemStack(lapotronpack));
        OreDictionary.registerOre("gearBronze", new ItemStack(parts, 1, 20));
        OreDictionary.registerOre("gearIron", new ItemStack(parts, 1, 21));
        OreDictionary.registerOre("gearTitanium", new ItemStack(parts, 1, 22));
        OreDictionary.registerOre("gearSteel", new ItemStack(parts, 1, 23));
        OreDictionary.registerOre("gearTungstensteel", new ItemStack(parts, 1, 24));
		OreDictionary.registerOre("blockLapis", new ItemStack(parts, 1, 27));

	}

}
