/*
 * This file is part of RebornCore, licensed under the MIT License (MIT).
 *
 * Copyright (c) 2021 TeamReborn
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Date: 27/11/2016 17:33:21
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package reborncore.client;

import net.minecraft.client.model.ModelPart;
import net.minecraft.client.network.AbstractClientPlayerEntity;
import net.minecraft.client.render.VertexConsumer;
import net.minecraft.client.render.entity.model.EntityModel;
import net.minecraft.client.util.math.MatrixStack;

import java.util.Arrays;
import java.util.Collections;

public class ModelSantaHat extends EntityModel<AbstractClientPlayerEntity> {
	private final ModelPart hatband1;
	private final ModelPart hatband2;
	private final ModelPart hatband3;
	private final ModelPart hatband4;
	private final ModelPart hatbase1;
	private final ModelPart hatband5;
	private final ModelPart hatband6;
	private final ModelPart hatbase2;
	private final ModelPart hatextension1;
	private final ModelPart hatextension2;
	private final ModelPart hatextension3;
	private final ModelPart hatextension4;
	private final ModelPart hatball1;
	private final ModelPart hatball2;
	private final ModelPart hatball3;
	private final ModelPart hatball4;
	private final ModelPart hatball5;
	private final ModelPart hatball6;

	public ModelSantaHat() {
		ModelPart.Cuboid[] hatband1Cuboids = {
			new ModelPart.Cuboid(0, 32, -4F, -8F, -5F, 8F, 1F, 1F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatband1 = new ModelPart(Arrays.asList(hatband1Cuboids), Collections.emptyMap());
		hatband1.setPivot(0F, 0F, 0F);
		setRotation(hatband1, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatband2Cuboids = {
			new ModelPart.Cuboid(0, 32, -4F, -8F, 4F, 8F, 1F, 1F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatband2 = new ModelPart(Arrays.asList(hatband2Cuboids), Collections.emptyMap());
		hatband2.setPivot(0F, 0F, 0F);
		setRotation(hatband2, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatband3Cuboids = {
			new ModelPart.Cuboid(0, 34, -5F, -8F, -4F, 1F, 1F, 8F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatband3 = new ModelPart(Arrays.asList(hatband3Cuboids), Collections.emptyMap());
		hatband3.setPivot(0F, 0F, 0F);
		setRotation(hatband3, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatband4Cuboids = {
			new ModelPart.Cuboid(0, 34, 4F, -8F, -4F, 1F, 1F, 8F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatband4 = new ModelPart(Arrays.asList(hatband4Cuboids), Collections.emptyMap());
		hatband4.setPivot(0F, 0F, 0F);
		setRotation(hatband4, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatbase1Cuboids = {
			new ModelPart.Cuboid(0, 43, -4F, -9F, -4F, 8F, 1F, 8F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatbase1 = new ModelPart(Arrays.asList(hatbase1Cuboids), Collections.emptyMap());
		hatbase1.setPivot(0F, 0F, 0F);
		setRotation(hatbase1, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatband5Cuboids = {
			new ModelPart.Cuboid(18, 41, 0F, -7F, -5F, 4F, 1F, 1F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatband5 = new ModelPart(Arrays.asList(hatband5Cuboids), Collections.emptyMap());
		hatband5.setPivot(0F, 0F, 0F);
		setRotation(hatband5, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatband6Cuboids = {
			new ModelPart.Cuboid(18, 41, -4F, -7F, 0F, 4F, 1F, 1F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatband6 = new ModelPart(Arrays.asList(hatband6Cuboids), Collections.emptyMap());
		hatband6.setPivot(0F, 0F, 4F);
		setRotation(hatband6, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatbase2Cuboids = {
			new ModelPart.Cuboid(18, 34, -3F, -10F, -3F, 6F, 1F, 6F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatbase2 = new ModelPart(Arrays.asList(hatbase2Cuboids), Collections.emptyMap());
		hatbase2.setPivot(0F, 0F, 0F);
		setRotation(hatbase2, 0F, 0.1115358F, 0F);

		ModelPart.Cuboid[] hatextension1Cuboids = {
			new ModelPart.Cuboid(0, 52, -3F, -11F, -2F, 4F, 2F, 4F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatextension1 = new ModelPart(Arrays.asList(hatextension1Cuboids), Collections.emptyMap());
		hatextension1.setPivot(0F, 0F, 0F);
		setRotation(hatextension1, 0F, -0.0371786F, 0.0743572F);

		ModelPart.Cuboid[] hatextension2Cuboids = {
			new ModelPart.Cuboid(16, 52, -2.4F, -12F, -1.5F, 3F, 2F, 3F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatextension2 = new ModelPart(Arrays.asList(hatextension2Cuboids), Collections.emptyMap());
		hatextension2.setPivot(0F, 0F, 0F);
		setRotation(hatextension2, 0F, 0.0743572F, 0.0743572F);

		ModelPart.Cuboid[] hatextension3Cuboids = {
			new ModelPart.Cuboid(28, 52, -3.5F, -13F, -1F, 2F, 2F, 2F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatextension3 = new ModelPart(Arrays.asList(hatextension3Cuboids), Collections.emptyMap());
		hatextension3.setPivot(0F, 0F, 0F);
		setRotation(hatextension3, 0F, 0F, 0.2230717F);

		ModelPart.Cuboid[] hatextension4Cuboids = {
			new ModelPart.Cuboid(0, 58, -13F, -6.6F, -1F, 2F, 3F, 2F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatextension4 = new ModelPart(Arrays.asList(hatextension4Cuboids), Collections.emptyMap());
		hatextension4.setPivot(0F, 0F, 0F);
		setRotation(hatextension4, 0F, 0F, 1.264073F);

		ModelPart.Cuboid[] hatball1Cuboids = {
			new ModelPart.Cuboid(8, 58, 2F, -14.4F, -1.001F, 2F, 2F, 2F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatball1 = new ModelPart(Arrays.asList(hatball1Cuboids), Collections.emptyMap());
		hatball1.setPivot(0F, 0F, 0F);
		setRotation(hatball1, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatball2Cuboids = {
			new ModelPart.Cuboid(16, 57, 2.5F, -14.8F, -0.5F, 1F, 1F, 1F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatball2 = new ModelPart(Arrays.asList(hatball2Cuboids), Collections.emptyMap());
		hatball2.setPivot(0F, 0F, 0F);
		setRotation(hatball2, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatball3Cuboids = {
			new ModelPart.Cuboid(16, 57, 2.5F, -13F, -0.5F, 1F, 1F, 1F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatball3 = new ModelPart(Arrays.asList(hatball3Cuboids), Collections.emptyMap());
		hatball3.setPivot(0F, 0F, 0F);
		setRotation(hatball3, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatball4Cuboids = {
			new ModelPart.Cuboid(16, 57, 3.4F, -14F, -0.5F, 1F, 1F, 1F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatball4 = new ModelPart(Arrays.asList(hatball4Cuboids), Collections.emptyMap());
		hatball4.setPivot(0F, 0F, 0F);
		setRotation(hatball4, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatball5Cuboids = {
			new ModelPart.Cuboid(16, 57, 2.5F, -14F, 0.4F, 1F, 1F, 1F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatball5 = new ModelPart(Arrays.asList(hatball5Cuboids), Collections.emptyMap());
		hatball5.setPivot(0F, 0F, 0F);
		setRotation(hatball5, 0F, 0F, 0F);

		ModelPart.Cuboid[] hatball6Cuboids = {
			new ModelPart.Cuboid(16, 57, 2.5F, -14F, -1.4F, 1F, 1F, 1F, 0F, 0F, 0F, true, 64F, 64F)
		};
		hatball6 = new ModelPart(Arrays.asList(hatball6Cuboids), Collections.emptyMap());
		hatball6.setPivot(0F, 0F, 0F);
		setRotation(hatball6, 0F, 0F, 0F);
	}

	@Override
	public void setAngles(AbstractClientPlayerEntity entity, float limbAngle, float limbDistance, float age, float headYaw, float headPitch) {

	}

	@Override
	public void render(MatrixStack matrixStack, VertexConsumer vertexConsumer, int light, int overlay, float r, float g, float b, float f) {
		hatband1.render(matrixStack, vertexConsumer, light, overlay);
		hatband2.render(matrixStack, vertexConsumer, light, overlay);
		hatband3.render(matrixStack, vertexConsumer, light, overlay);
		hatband4.render(matrixStack, vertexConsumer, light, overlay);
		hatbase1.render(matrixStack, vertexConsumer, light, overlay);
		hatband5.render(matrixStack, vertexConsumer, light, overlay);
		hatband6.render(matrixStack, vertexConsumer, light, overlay);
		hatbase2.render(matrixStack, vertexConsumer, light, overlay);
		hatextension1.render(matrixStack, vertexConsumer, light, overlay);
		hatextension2.render(matrixStack, vertexConsumer, light, overlay);
		hatextension3.render(matrixStack, vertexConsumer, light, overlay);
		hatextension4.render(matrixStack, vertexConsumer, light, overlay);
		hatball1.render(matrixStack, vertexConsumer, light, overlay);
		hatball2.render(matrixStack, vertexConsumer, light, overlay);
		hatball3.render(matrixStack, vertexConsumer, light, overlay);
		hatball4.render(matrixStack, vertexConsumer, light, overlay);
		hatball5.render(matrixStack, vertexConsumer, light, overlay);
		hatball6.render(matrixStack, vertexConsumer, light, overlay);
	}

	private void setRotation(ModelPart model, float x, float y, float z) {
		model.pitch = x;
		model.yaw = y;
		model.roll = z;
	}

}
